export interface HeatPumpState {
    PCycleActual: number;
    NumberOfFanSpeeds: number;
    UseTemperatureA: boolean;
    TemperatureIncrementOverride: number;
    TemperatureIncrement: number;
    MinTempCoolDry: number;
    MaxTempCoolDry: number;
    MinTempHeat: number;
    MaxTempHeat: number;
    MinTempAutomatic: number;
    MaxTempAutomatic: number;
    LegacyDevice: boolean;
    UnitSupportsStandbyMode: boolean;
    IsSplitSystem: boolean;
    HasHalfDegreeIncrements: boolean;
    HasOutdoorTemperature: boolean;
    ModelIsAirCurtain: boolean;
    ModelSupportsFanSpeed: boolean;
    ModelSupportsAuto: boolean;
    ModelSupportsHeat: boolean;
    ModelSupportsDry: boolean;
    ModelSupportsVaneVertical: boolean;
    ModelSupportsVaneHorizontal: boolean;
    ModelSupportsWideVane: boolean;
    ModelDisableEnergyReport: boolean;
    ModelSupportsStandbyMode: boolean;
    ModelSupportsEnergyReporting: boolean;
    ProhibitSetTemperature: boolean;
    ProhibitOperationMode: boolean;
    ProhibitPower: boolean;
    Power: boolean;
    RoomTemperature: number;
    OutdoorTemperature: number;
    SetTemperature: number;
    ActualFanSpeed: number;
    FanSpeed: number;
    AutomaticFanSpeed: boolean;
    VaneVerticalDirection: number;
    VaneVerticalSwing: boolean;
    VaneHorizontalDirection: number;
    VaneHorizontalSwing: boolean;
    OperationMode: number;
    EffectiveFlags: number;
    LastEffectiveFlags: number;
    InStandbyMode: boolean;
    DemandPercentage: number;
    ConfiguredDemandPercentage: number | null;
    HasDemandSideControl: boolean;
    DefaultCoolingSetTemperature: number;
    DefaultHeatingSetTemperature: number;
    RoomTemperatureLabel: number;
    HeatingEnergyConsumedRate1: number;
    HeatingEnergyConsumedRate2: number;
    CoolingEnergyConsumedRate1: number;
    CoolingEnergyConsumedRate2: number;
    AutoEnergyConsumedRate1: number;
    AutoEnergyConsumedRate2: number;
    DryEnergyConsumedRate1: number;
    DryEnergyConsumedRate2: number;
    FanEnergyConsumedRate1: number;
    FanEnergyConsumedRate2: number;
    OtherEnergyConsumedRate1: number;
    OtherEnergyConsumedRate2: number;
    EstimateAtaEnergyProduction: boolean;
    EstimateAtaEnergyProductionOptIn: boolean;
    EstimateAtaEnergyProductionOptInTimestamp: string | null;
    WeatherForecast: any[];
    HasEnergyConsumedMeter: boolean;
    CurrentEnergyConsumed: number;
    CurrentEnergyMode: number;
    CoolingDisabled: boolean;
    EnergyCorrectionModel: number;
    EnergyCorrectionActive: boolean;
    MinPcycle: number;
    MaxPcycle: number;
    EffectivePCycle: number;
    MaxOutdoorUnits: number;
    MaxIndoorUnits: number;
    MaxTemperatureControlUnits: number;
    ModelCode: string;
    DeviceID: number;
    MacAddress: string;
    SerialNumber: string;
    TimeZoneID: number;
    DiagnosticMode: number;
    DiagnosticEndDate: string | null;
    ExpectedCommand: number;
    Owner: number;
    DetectedCountry: string | null;
    AdaptorType: number;
    FirmwareDeployment: string | null;
    FirmwareUpdateAborted: boolean;
    FlashWrites: number;
    Scene: string | null;
    SSLExpirationDate: string;
    SPTimeout: number;
    Passcode: string | null;
    Units: Unit[];
}

export interface Unit {
    SerialNumber: string;
    ModelNumber: number;
    Model: string;
    UnitType: number;
    IsIndoor: boolean;
}